<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
    Play, Download, Sparkles, ArrowLeft,
    Loader2, Scissors
} from 'lucide-vue-next'
import api from '../../utils/axios'
import { useNotificationStore } from '../../stores/notifications'
import VideoModal from './VideoModal.vue'

const route = useRoute()
const router = useRouter()
const notify = useNotificationStore()

const videoId = route.params.id
const clips = ref([])
const isLoading = ref(true)

const selectedClip = ref(null)
const isModalOpen = ref(false)

// Ambil URL thumbnail langsung dari data backend
const getThumbnailUrl = (clip) => {
    return clip.thumbnail_url || '/placeholder-thumb.jpg';
}

const fetchClips = async () => {
    isLoading.value = true
    try {
        // Endpoint untuk mengambil klip berdasarkan video_id
        const response = await api.get(`/videos/${videoId}/clips`)

        // Gunakan endpoint stream resmi agar video bisa diputar di browser
        clips.value = response.data.data.map(clip => ({
            ...clip,
            clip_url: `http://localhost:8000/api/clips/${clip.id}/stream`
        }))

    } catch (error) {
        const errorMsg = error.response?.data?.message || 'Gagal memuat klip dari server.'
        notify.show(errorMsg, 'error')
    } finally {
        isLoading.value = false
    }
}

const openPreview = (clip) => {
    selectedClip.value = clip
    isModalOpen.value = true
}

const handleDownload = (clipId) => {
    if (!clipId) return
    // Endpoint download resmi yang melakukan redirect ke storage
    const downloadUrl = `http://localhost:8000/api/clips/${clipId}/download`
    window.open(downloadUrl, '_blank')
}

onMounted(fetchClips)
</script>

<template>
    <div class="min-h-screen bg-[#0B0F17] font-sans text-white p-6">
        <div class="max-w-7xl mx-auto">
            <header class="flex items-center justify-between mb-8">
                <div class="flex items-center gap-4">
                    <button @click="router.push('/dashboard')"
                        class="p-2 bg-gray-900 rounded-lg border border-gray-800 hover:bg-gray-800 transition-all text-gray-400">
                        <ArrowLeft class="w-4 h-4" />
                    </button>
                    <div>
                        <h1 class="text-xl font-black tracking-tighter uppercase italic leading-none text-white">
                            Viral Clips
                        </h1>
                        <p class="text-gray-500 text-[10px] font-bold mt-1 uppercase tracking-[0.2em]">
                            {{ clips.length }} Highlights Generated by AI
                        </p>
                    </div>
                </div>

                <button
                    class="flex items-center gap-2 px-6 py-3 bg-emerald-500 text-black rounded-2xl font-black text-[11px] uppercase tracking-widest hover:scale-105 transition-all shadow-lg shadow-emerald-500/20">
                    <Sparkles class="w-4 h-4" /> Export All
                </button>
            </header>

            <div v-if="!isLoading && clips.length > 0"
                class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
                <div v-for="clip in clips" :key="clip.id"
                    class="bg-gray-900/40 rounded-[2.5rem] border border-white/5 overflow-hidden group hover:border-emerald-500/40 transition-all duration-500 flex flex-col shadow-2xl">

                    <div class="relative aspect-3/4 bg-black overflow-hidden cursor-pointer"
                        @click="openPreview(clip)">
                        <img :src="getThumbnailUrl(clip)" @error="(e) => e.target.src = '/placeholder-thumb.jpg'"
                            class="w-full h-full object-cover opacity-80 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700" />
                        <div class="absolute top-4 left-4">
                            <div
                                class="bg-emerald-500 px-3 py-1 rounded-full text-black text-[10px] font-black flex items-center gap-1.5 shadow-xl">
                                <Sparkles class="w-3 h-3 fill-current" /> {{ clip.viral_score }} SCORE
                            </div>
                        </div>
                        <div
                            class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all duration-300">
                            <div
                                class="p-5 bg-white/10 backdrop-blur-xl rounded-full text-white border border-white/20 scale-75 group-hover:scale-100 transition-all">
                                <Play class="w-6 h-6 fill-current" />
                            </div>
                        </div>
                    </div>

                    <div class="p-6 flex flex-col gap-5 bg-gray-900/40 border-t border-white/5">
                        <h3
                            class="font-bold text-[13px] text-white line-clamp-2 leading-tight h-10 group-hover:text-emerald-500 transition-colors">
                            {{ clip.title || 'Untitled Clip' }}
                        </h3>
                        <div class="flex flex-col gap-2">
                            <div class="flex gap-2">
                                <button @click="router.push(`/dashboard/clips/${clip.id}/edit`)"
                                    class="flex-1 flex items-center justify-center gap-2 bg-emerald-500/10 text-emerald-500 py-3 rounded-2xl font-black text-[9px] uppercase tracking-widest hover:bg-emerald-500 hover:text-black transition-all border border-emerald-500/20">
                                    <Scissors class="w-4 h-4" /> Edit
                                </button>
                                <button @click="openPreview(clip)"
                                    class="flex-1 flex items-center justify-center gap-2 bg-white/5 text-white py-3 rounded-2xl font-black text-[9px] uppercase tracking-widest hover:bg-white hover:text-black transition-all border border-white/10">
                                    <Play class="w-3.5 h-3.5" /> Watch
                                </button>
                            </div>
                            <button @click="handleDownload(clip.id)"
                                class="w-full flex items-center justify-center gap-2 bg-gray-800 text-gray-400 py-3 rounded-2xl font-black text-[9px] uppercase tracking-widest hover:bg-gray-700 hover:text-white transition-all border border-white/5">
                                <Download class="w-3.5 h-3.5" /> Download Clip
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div v-if="!isLoading && clips.length === 0"
                class="flex flex-col items-center justify-center py-40 text-center">
                <div
                    class="w-24 h-24 bg-gray-900 rounded-[2.5rem] flex items-center justify-center mb-8 border border-gray-800 shadow-inner">
                    <Loader2 class="w-10 h-10 text-emerald-500 animate-spin" />
                </div>
                <h3 class="text-xl font-black text-white mb-2 uppercase italic tracking-tighter">AI Analysis in Progress
                </h3>
                <p class="text-gray-500 text-[10px] max-w-xs mx-auto leading-relaxed uppercase tracking-[0.2em]">
                    Sedang transkripsi audio dan analisis highlight viral via Gemini API...
                </p>
            </div>

            <VideoModal :is-open="isModalOpen" :clip="selectedClip" @close="isModalOpen = false" />
        </div>
    </div>
</template>